version: '3'

services:
  registry-web:
    container_name: registry-web
    image: hyper/docker-registry-web:latest
    volumes:
       - ./conf/registry-web:/conf:ro
       - ./db:/data
    networks:
      - registry-net
    depends_on:
       - registry

  registry:
    container_name: registry
    image: registry:2.8.1
    volumes:
      - ./conf/registry:/etc/docker/registry:ro
    networks:
      - registry-net

networks:
  registry-net:
